---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-tech-trend
  labels:
    app: stock-tech-trend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-tech-trend
  template:
    metadata:
      labels:
        app: stock-tech-trend
    spec:
      containers:
        - name: stock-tech-trend
          image: stock-tech-trend:latest
          ports:
            - containerPort: 8080
